// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/checkout": {
    params: {};
  };
  "/checkout/success": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/towels": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/wishlist": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/login": {
    params: {};
  };
  "/account/register": {
    params: {};
  };
  "/order/status/:id": {
    params: {
      "id": string;
    };
  };
  "/order/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/order/:id/return": {
    params: {
      "id": string;
    };
  };
  "/api/shipping-rates": {
    params: {};
  };
  "/api/checkout-session": {
    params: {};
  };
  "/api/carts": {
    params: {};
  };
  "/api/carts/:id": {
    params: {
      "id": string;
    };
  };
  "/api/carts/:id/shipping-options": {
    params: {
      "id": string;
    };
  };
  "/api/carts/:id/shipping-methods": {
    params: {
      "id": string;
    };
  };
  "/api/carts/:id/complete": {
    params: {
      "id": string;
    };
  };
  "/api/payment-collections": {
    params: {};
  };
  "/api/payment-collections/:id/sessions": {
    params: {
      "id": string;
    };
  };
  "/api/health": {
    params: {};
  };
  "/api/set-guest-token": {
    params: {};
  };
  "/blog/:id": {
    params: {
      "id": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products/:handle" | "/collections/:handle" | "/checkout" | "/checkout/success" | "/about" | "/blog" | "/towels" | "/search" | "/wishlist" | "/account" | "/account/login" | "/account/register" | "/order/status/:id" | "/order/:id/edit" | "/order/:id/return" | "/api/shipping-rates" | "/api/checkout-session" | "/api/carts" | "/api/carts/:id" | "/api/carts/:id/shipping-options" | "/api/carts/:id/shipping-methods" | "/api/carts/:id/complete" | "/api/payment-collections" | "/api/payment-collections/:id/sessions" | "/api/health" | "/api/set-guest-token" | "/blog/:id" | "/sitemap.xml" | "/robots.txt";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/collections.$handle.tsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/checkout.success.tsx": {
    id: "routes/checkout.success";
    page: "/checkout/success";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/towels.tsx": {
    id: "routes/towels";
    page: "/towels";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/wishlist.tsx": {
    id: "routes/wishlist";
    page: "/wishlist";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/account.login.tsx": {
    id: "routes/account.login";
    page: "/account/login";
  };
  "routes/account.register.tsx": {
    id: "routes/account.register";
    page: "/account/register";
  };
  "routes/order_.status.$id.tsx": {
    id: "routes/order_.status.$id";
    page: "/order/status/:id";
  };
  "routes/order_.$id.edit.tsx": {
    id: "routes/order_.$id.edit";
    page: "/order/:id/edit";
  };
  "routes/order_.$id.return.tsx": {
    id: "routes/order_.$id.return";
    page: "/order/:id/return";
  };
  "routes/api.shipping-rates.ts": {
    id: "routes/api.shipping-rates";
    page: "/api/shipping-rates";
  };
  "routes/api.checkout-session.ts": {
    id: "routes/api.checkout-session";
    page: "/api/checkout-session";
  };
  "routes/api.carts.ts": {
    id: "routes/api.carts";
    page: "/api/carts";
  };
  "routes/api.carts.$id.ts": {
    id: "routes/api.carts.$id";
    page: "/api/carts/:id";
  };
  "routes/api.carts.$id.shipping-options.ts": {
    id: "routes/api.carts.$id.shipping-options";
    page: "/api/carts/:id/shipping-options";
  };
  "routes/api.carts.$id.shipping-methods.ts": {
    id: "routes/api.carts.$id.shipping-methods";
    page: "/api/carts/:id/shipping-methods";
  };
  "routes/api.carts.$id.complete.ts": {
    id: "routes/api.carts.$id.complete";
    page: "/api/carts/:id/complete";
  };
  "routes/api.payment-collections.ts": {
    id: "routes/api.payment-collections";
    page: "/api/payment-collections";
  };
  "routes/api.payment-collections.$id.sessions.ts": {
    id: "routes/api.payment-collections.$id.sessions";
    page: "/api/payment-collections/:id/sessions";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.set-guest-token.ts": {
    id: "routes/api.set-guest-token";
    page: "/api/set-guest-token";
  };
  "routes/blog.$id.tsx": {
    id: "routes/blog.$id";
    page: "/blog/:id";
  };
  "routes/sitemap[.]xml.tsx": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/robots[.]txt.tsx": {
    id: "routes/robots[.]txt";
    page: "/robots.txt";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/checkout.success": typeof import("./app/routes/checkout.success.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/blog": typeof import("./app/routes/blog.tsx");
  "routes/towels": typeof import("./app/routes/towels.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/wishlist": typeof import("./app/routes/wishlist.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account.login": typeof import("./app/routes/account.login.tsx");
  "routes/account.register": typeof import("./app/routes/account.register.tsx");
  "routes/order_.status.$id": typeof import("./app/routes/order_.status.$id.tsx");
  "routes/order_.$id.edit": typeof import("./app/routes/order_.$id.edit.tsx");
  "routes/order_.$id.return": typeof import("./app/routes/order_.$id.return.tsx");
  "routes/api.shipping-rates": typeof import("./app/routes/api.shipping-rates.ts");
  "routes/api.checkout-session": typeof import("./app/routes/api.checkout-session.ts");
  "routes/api.carts": typeof import("./app/routes/api.carts.ts");
  "routes/api.carts.$id": typeof import("./app/routes/api.carts.$id.ts");
  "routes/api.carts.$id.shipping-options": typeof import("./app/routes/api.carts.$id.shipping-options.ts");
  "routes/api.carts.$id.shipping-methods": typeof import("./app/routes/api.carts.$id.shipping-methods.ts");
  "routes/api.carts.$id.complete": typeof import("./app/routes/api.carts.$id.complete.ts");
  "routes/api.payment-collections": typeof import("./app/routes/api.payment-collections.ts");
  "routes/api.payment-collections.$id.sessions": typeof import("./app/routes/api.payment-collections.$id.sessions.ts");
  "routes/api.health": typeof import("./app/routes/api.health.ts");
  "routes/api.set-guest-token": typeof import("./app/routes/api.set-guest-token.ts");
  "routes/blog.$id": typeof import("./app/routes/blog.$id.tsx");
  "routes/sitemap[.]xml": typeof import("./app/routes/sitemap[.]xml.tsx");
  "routes/robots[.]txt": typeof import("./app/routes/robots[.]txt.tsx");
};